### ISSUE TITLE
mft2 uses raw buffer (uInt8Number) instead of typedBuffer (uInt16Number)

### ISSUE THREAD

**Issue by dlabz** [dlabz/icc#1]
This might not really be needed, as 

```yaml
          lut_16_type:
            seq:
              - id: reserved
                contents: [0x00, 0x00, 0x00, 0x00]
              - id: number_of_input_channels
                type: u1
              - id: number_of_output_channels
                type: u1
              - id: number_of_clut_grid_points
                type: u1
              - id: padding
                contents: [0x00]
              - id: encoded_e_parameters
                type: s4
                repeat: expr
                repeat-expr: 9
              - id: number_of_input_table_entries
                type: u4
              - id: number_of_output_table_entries
                type: u4
              - id: input_tables
                size: 2 * number_of_input_channels * number_of_input_table_entries
              - id: clut_values
                size: 2 * (number_of_clut_grid_points ^ number_of_input_channels) * number_of_output_channels
              - id: output_tables
                size: 2 * number_of_output_channels * number_of_output_table_entries
```
```yaml
          lut_8_type:
            seq:
              - id: reserved
                contents: [0x00, 0x00, 0x00, 0x00]
              - id: number_of_input_channels
                type: u1
              - id: number_of_output_channels
                type: u1
              - id: number_of_clut_grid_points
                type: u1
              - id: padding
                contents: [0x00]
              - id: encoded_e_parameters
                type: s4
                repeat: expr
                repeat-expr: 9
              - id: number_of_input_table_entries
                type: u4
              - id: number_of_output_table_entries
                type: u4
              - id: input_tables
                size: 256 * number_of_input_channels
              - id: clut_values
                size: (number_of_clut_grid_points ^ number_of_input_channels) * number_of_output_channels
              - id: output_tables
                size: 256 * number_of_output_channels

```
